# Defining Efficient Data Loaders

How to set up a `DataLoader` for a folder containing image files.

# Obtaining the Dataset

- This downloads the datasets png files:

In [2]:
!git clone "https://github.com/rasbt/mnist-pngs"

Cloning into 'mnist-pngs'...
Updating files: 100% (70006/70006), done.

In [10]:
import os
import pandas as pd

base_path = "mnist-pngs"

def build_csv(split):
    rows = []
    split_path = os.path.join(base_path, split)

    for label in sorted(os.listdir(split_path), key=int):
        label_path = os.path.join(split_path, label)

        if not os.path.isdir(label_path):
            continue

        for img in sorted(os.listdir(label_path)):
            if img.endswith(".png"):
                rows.append({
                    "file_path": os.path.join(split, label, img),
                    "label": int(label)
                })

    return pd.DataFrame(rows)

df_train = build_csv("train")
df_test  = build_csv("test")

In [11]:
df_train.to_csv(os.path.join(base_path,"train.csv"), index=False)
df_test.to_csv(os.path.join(base_path,"test.csv"), index=False)

# CSV

- Here, we check the CSV files listing the image names and labels

In [12]:
df_train.head()

           file_path  label
0      train/0/1.png      0
1   train/0/1000.png      0
2  train/0/10005.png      0
3  train/0/10010.png      0
4  train/0/10022.png      0

In [13]:
df_test = pd.read_csv('mnist-pngs/test.csv')
df_test.head()

          file_path  label
0  test/0/60003.png      0
1  test/0/60010.png      0
2  test/0/60013.png      0
3  test/0/60025.png      0
4  test/0/60028.png      0

## Creating a validation split

- MNIST doesn't come with a validation set partition, so we are creating it here from the training set, using 10% of the training data for validation.

In [14]:
df_train = df_train.sample(frac=1, random_state=123)

loc = round(df_train.shape[0]*0.9)
df_new_train = df_train.iloc[:loc]
df_new_val = df_train.iloc[loc:]

df_new_train.to_csv('mnist-pngs/new_train.csv', index=None)
df_new_val.to_csv('mnist-pngs/new_val.csv', index=None)

In [15]:
df_new_train.head()

               file_path  label
15280  train/8/27425.png      8
14487  train/8/19879.png      8
10431  train/5/45963.png      5
2138   train/0/29677.png      0
5506   train/2/30811.png      2

In [16]:
df_new_val.head()

               file_path  label
10349  train/5/45124.png      5
6047   train/3/13704.png      3
4021   train/2/17448.png      2
5622   train/3/10093.png      3
14519   train/8/2016.png      8